services:
  starter-db:
    image: postgres:11.12
    container_name: starter-db
    env_file:
      - ./server/.env.database
    ports:
      - "5432:5432"
    networks:
      - starter-net
    volumes:
      - ./server/dbdata:/var/lib/postgresql/data

  redis-server:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - starter-net
    volumes:
      -  ./server/redis_data:/bitnami/redis/data
    depends_on:
      - starter-db

  starter-web:
    build: ./web
    container_name: starter-web
    env_file:
      - ./web/.env.local
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - starter-net
    depends_on:
      - starter-server
    volumes:
      - ./web:/app
    entrypoint: ["yarn", "dev"]

  starter-server:
    build: ./server
    container_name: starter-server
    env_file:
      - ./server/.env.development
    expose:
      - "4000"
    ports:
      - "4000:4000"
    networks:
      - starter-net
    depends_on:
      - redis-server
      - starter-db
    volumes:
      - ./server:/app
    command: /bin/sh "./entrypoint.sh"

networks:
  starter-net:
